import 'package:flutter/material.dart';

class Video {
  final String id;
  final String title;
  final String url;
  final String imageUrl;
  final int activityLevel;
  final String name;
  final String author;
  final String target;
  Video(this.id, this.title, this.url, this.imageUrl, this.activityLevel,
      this.name, this.author, this.target);
}

//Lists of: abs, arm, back ,chest, glute, leg, shoulder
final List<Video> abs = [
  Video(
      '2',
      '30 Variations of Ab exercises!',
      'https://www.youtube.com/watch?v=snuxyjy1jhg',
      'https://img.youtube.com/vi/snuxyjy1jhg/0.jpg',
      3,
      'Ab Routine',
      'Jordan Yeoh Fitness',
      'abs'),
  Video(
      '3',
      'Standing Ab Workout',
      'https://www.youtube.com/watch?v=64cXpMTv6CE',
      'https://img.youtube.com/vi/64cXpMTv6CE/0.jpg',
      4,
      'Standing Cable Adominal Routine',
      "ATHLEAN-X",
      'abs'),
  Video(
      '4',
      'How to Do a Leg Raise | Ab Workout',
      'https://www.youtube.com/watch?v=l4kQd9eWclE',
      'https://img.youtube.com/vi/l4kQd9eWclE/0.jpg',
      2,
      "Leg Raise",
      "Howcast",
      'abs'),
  Video(
      '5',
      '3 MINUTE AB WORKOUT | EASY',
      'https://www.youtube.com/watch?v=JgeRv3L4k-U',
      'https://img.youtube.com/vi/JgeRv3L4k-U/0.jpg',
      1,
      "Adominal Routine",
      "Chengman",
      'abs'),
  Video(
      '6',
      'COMPLETE BENCH ABS WORKOUT / 4 BEST ABS EXS USING JUST BENCH',
      'https://www.youtube.com/watch?v=pCO1D-dTFwM',
      'https://img.youtube.com/vi/pCO1D-dTFwM/0.jpg',
      2,
      "Abdominal Bench Routine",
      "MUSCLE MIND EMOTION",
      'abs'),
  Video(
      '7',
      'Abdominal Crunch',
      'https://www.youtube.com/watch?v=_M2Etme-tfE',
      'https://img.youtube.com/vi/_M2Etme-tfE/0.jpg',
      1,
      'Adominal Crunches',
      'Passion4Profession',
      'abs'),
  Video(
      '8',
      '1 Minute SIX PACK Abs - STANDING Core Routine with Dumbbells',
      'https://www.youtube.com/watch?v=f47t73qeSac',
      'https://img.youtube.com/vi/f47t73qeSac/0.jpg',
      4,
      "Dumbell Abdominal Routine",
      "Criticalbench",
      'abs'),
];

final List<Video> arm = [
  Video(
      '1',
      'The Perfect Pull Up - Do it right!',
      'https://www.youtube.com/watch?v=eGo4IYlbE5g&ab_channel=Calisthenicmovement',
      'https://img.youtube.com/vi/eGo4IYlbE5g/0.jpg',
      1,
      "Pull ups",
      "Calisthenicmovement",
      'arms'),
  Video(
      '2',
      'How to Do Triceps Kick Backs',
      'https://www.youtube.com/watch?v=ZO81bExngMI&ab_channel=LIVESTRONG.COM',
      'https://img.youtube.com/vi/ZO81bExngMI/0.jpg',
      1,
      "Triceps Kick Backs",
      "LIVESTRONG.COM",
      'arms'),
  Video(
      '3',
      'How To: Dumbbell Concentration Curl',
      'https://www.youtube.com/watch?v=Jvj2wV0vOYU&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/Jvj2wV0vOYU/0.jpg',
      1,
      "Concentration Curl",
      "ScottHermanFitness",
      'arms'),
  Video(
      '4',
      'How To: Dumbbell Floor Press',
      'https://www.youtube.com/watch?v=uUGDRwge4F8&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/uUGDRwge4F8/0.jpg',
      2,
      "Dumbbell Floor press",
      "ScottHermanFitness",
      'arms'),
  Video(
      //GOOD
      '5',
      'How to Do a Barbell Curl | Arm Workout',
      'https://www.youtube.com/watch?v=kwG2ipFRgfo',
      'https://img.youtube.com/vi/kwG2ipFRgfo/0.jpg',
      2,
      "Barbell curl",
      "Howcast",
      'arms'),
  Video(
      '6',
      'Supinated Bicep Curl',
      'https://www.youtube.com/watch?v=k6gAgAYxlTg&ab_channel=WigAthletics',
      'https://img.youtube.com/vi/k6gAgAYxlTg/0.jpg',
      2,
      "Supinated Bicep Curl",
      "Wig Athletics",
      'arms'),
  Video(
      '7',
      'How To: Dumbbell Hammer Curl',
      'https://www.youtube.com/watch?v=zC3nLlEvin4&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/zC3nLlEvin4/0.jpg',
      1,
      "Dumbbell Hammer Curl",
      "ScottHermanFitness",
      'arms'),
  Video(
      '8',
      'How to Do a Hammer Curl | Arm Workout',
      'https://www.youtube.com/watch?v=TwD-YGVP4Bk',
      'https://img.youtube.com/vi/TwD-YGVP4Bk/0.jpg',
      2,
      "Hammer-Curl",
      "Howcast",
      'arms'),
];

final List<Video> back = [
  Video(
      '1',
      'Wide-Grip Lat Pulldown | Back Exercise Guide',
      'https://www.youtube.com/watch?v=lueEJGjTuPQ',
      'https://img.youtube.com/vi/lueEJGjTuPQ/0.jpg',
      1,
      "Wide-Grip Lat Pulldown",
      "Bodybuilding.com",
      'back'),
  Video(
      '2',
      'How To: Seated Low Row (LF Cable)',
      'https://www.youtube.com/watch?v=GZbfZ033f74',
      'https://img.youtube.com/vi/GZbfZ033f74/0.jpg',
      1,
      "Seated Low Row (Cable)",
      "ScottHermanFitness",
      'back'),
  Video(
      '3',
      'How to Do a Dead Lift | Back Workout',
      'https://www.youtube.com/watch?v=DNJya2CBQJ8',
      'https://img.youtube.com/vi/DNJya2CBQJ8/0.jpg',
      3,
      "Deadlift",
      "Howcast",
      'back'),
  Video(
      '4',
      'How to Do a Dumbbell Row | Back Workout',
      'https://www.youtube.com/watch?v=-koP10y1qZI',
      'https://img.youtube.com/vi/-koP10y1qZI/0.jpg',
      1,
      "Dumbbell Row",
      "Howcast",
      'back'),
  Video(
      '5',
      'Prone Dumbbell Fly',
      'https://www.youtube.com/watch?v=vIwphYjZ0t8',
      'https://img.youtube.com/vi/vIwphYjZ0t8/0.jpg',
      1,
      "Prone Dumbbell Fly",
      "Discovery Learning",
      'back'),
  Video(
      '6',
      'Smith Machine Single Arm Rows',
      'https://www.youtube.com/watch?v=ewsa7vpoWdc',
      'https://img.youtube.com/vi/ewsa7vpoWdc/0.jpg',
      1,
      "Smith Machine Single Arm Rows",
      "Avid Fitness",
      'back'),
  Video(
      '7',
      'How To: T-Bar Row',
      'https://www.youtube.com/watch?v=j3Igk5nyZE4&t=49s&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/j3Igk5nyZE4/0.jpg',
      2,
      "T-bar Row",
      "ScottHermanFitness",
      'back'),
  Video(
      '8',
      'How To: Barbell Bent-Over Row',
      'https://www.youtube.com/watch?v=9efgcAjQe7E',
      'https://img.youtube.com/vi/9efgcAjQe7E/0.jpg',
      3,
      "Barbell Bent-Over Row",
      "ScottHermanFitness",
      'back'),
];

final List<Video> chest = [
  Video(
      '1',
      'How to Pump Up The Chest: Isometric Chest Exercises',
      'https://www.youtube.com/watch?v=3MR2QWZU9Ao&ab_channel=PearmanFitness',
      'https://img.youtube.com/vi/lhv2fhJaHz8/0.jpg',
      1,
      "Isometric Chest Exercises",
      "Pearman Fitness",
      "chest"),
  Video(
      '2',
      'How To: Decline Push-Up',
      'https://www.youtube.com/watch?v=SKPab2YC8BE&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/SKPab2YC8BE/0.jpg',
      3,
      "Decline Push-ups",
      "ScottHermanFitness",
      "chest"),
  Video(
      '3',
      'How To: Barbell Bench Press',
      'https://www.youtube.com/watch?v=rT7DgCr-3pg&ab_channel=ScottHermanFitness',
      'https://img.youtube.com/vi/rT7DgCr-3pg/0.jpg',
      1,
      "Barbell Bench press",
      "ScottHermanFitness",
      "chest"),
  Video(
      '4',
      'How to Do a Cable Chest Press | Chest Workout',
      'https://www.youtube.com/watch?v=FVWJglwid4I&ab_channel=Howcast',
      'https://img.youtube.com/vi/FVWJglwid4I/0.jpg',
      2,
      "Cable Chest Press",
      "Howcast",
      "chest"),
  Video(
      '5',
      'The Perfect Push Up | Do it right!',
      'https://www.youtube.com/watch?v=l-JwYtlm-PI',
      'https://img.youtube.com/vi/l-JwYtlm-PI/0.jpg',
      1,
      "Push-up",
      "Calisthenic Movement",
      "chest"),
  Video(
      '6',
      'How to Do an Incline Push-Up',
      'https://www.youtube.com/watch?v=bXsbK9UPu3c',
      'https://img.youtube.com/vi/bXsbK9UPu3c/0.jpg',
      2,
      "Incline Push-up",
      "Howcast",
      "chest"),
  Video(
      '7',
      'How to Do an Incline Dumbbell Fly',
      'https://www.youtube.com/watch?v=ajdFwa-qM98',
      'https://img.youtube.com/vi/ajdFwa-qM98/0.jpg',
      1,
      "Incline Dumbbell Fly",
      "Howcast",
      "chest"),
  Video(
      '8',
      'BUILD THE LOWER CHEST: Correct method using the DECLINE BENCH PRESS',
      'https://www.youtube.com/watch?v=NM5lbuq92Aw&ab_channel=MiamiMuscleUSA',
      'https://img.youtube.com/vi/NM5lbuq92Aw/0.jpg',
      5,
      "Decline Bench Press",
      "MiamiMuscleUSA",
      "chest"),
];

final List<Video> glute = [
  Video(
      '1',
      'How to PROPERLY Use the Abductor & Adductor Machine',
      'https://www.youtube.com/watch?v=h9BqUMqK-SY&ab_channel=ColossusFitness',
      'https://img.youtube.com/vi/h9BqUMqK-SY/0.jpg',
      1,
      "Abductor and Adductor",
      "ColossusFitness",
      "glute"),
  Video(
      '2',
      'How To Do A Knee Step-Up',
      'https://www.youtube.com/watch?v=VEV_b5zPZqY&ab_channel=FitazFK',
      'https://img.youtube.com/vi/VEV_b5zPZqY/0.jpg',
      1,
      "Knee Step-up",
      "FitazFk",
      "glute"),
  Video(
      '3',
      'Sumo Deadlift',
      'https://www.youtube.com/watch?v=nb-3H1dStfU',
      'https://img.youtube.com/vi/nb-3H1dStfU/0.jpg',
      4,
      "Sumo-Deadlift",
      "Physique Development",
      "glute"),
  Video(
      '4',
      'How To: Hip Thrust',
      'https://www.youtube.com/watch?v=SEdqd1n0cvg',
      'https://img.youtube.com/vi/SEdqd1n0cvg/0.jpg',
      3,
      "Hip Thrust",
      "ScottHermanFitness",
      "glute"),
  Video(
      '5',
      'How To Do A Glute Bridge | The Right Way | Well+Good',
      'https://www.youtube.com/watch?v=wPM8icPu6H8',
      'https://img.youtube.com/vi/wPM8icPu6H8/0.jpg',
      2,
      "Glute Bridge",
      "Well+Good",
      "glute"),
  Video(
      '6',
      'Master Dumbbell Lunges for Glutes',
      'https://www.youtube.com/watch?v=3frV3RnPfOY',
      'https://img.youtube.com/vi/3frV3RnPfOY/0.jpg',
      2,
      "Dumbbell Lunges",
      "BPI Sports",
      "glute"),
  Video(
      '7',
      'How to do Lunge Pulse | Joanna Soh',
      'https://www.youtube.com/watch?v=YCX2HGd0nLQ&ab_channel=ExerciseLibrary-JoannaSoh',
      'https://img.youtube.com/vi/YCX2HGd0nLQ/0.jpg',
      1,
      "Lunge Pulses",
      "Exercise Library - Joanna Soh",
      "glute"),
  Video(
      '8',
      'HOW TO PERFORM KICKBACKS',
      'https://www.youtube.com/watch?v=PoV-78Qzt_0',
      'https://img.youtube.com/vi/PoV-78Qzt_0/0.jpg',
      1,
      "Kickbacks",
      "Michele D'Angona",
      "glute"),
];

final List<Video> leg = [
  Video(
      '1',
      'Stiff Leg Deadlift',
      'https://www.youtube.com/watch?v=CkrqLaDGvOA',
      'https://img.youtube.com/vi/CkrqLaDGvOA/0.jpg',
      4,
      "Stiff leg Deadlift",
      "Muscle & Strength",
      "leg"),
  Video(
      '2',
      'Seated Calf Raise (Toes Neutral)',
      'https://www.youtube.com/watch?v=Yh5TXz99xwY',
      'https://img.youtube.com/vi/Yh5TXz99xwY/0.jpg',
      1,
      "Seated Calf Raise",
      "Muscle & Strength",
      "leg"),
  Video(
      '3',
      'How To: Standing Barbell Calf Raise',
      'https://www.youtube.com/watch?v=3UWi44yN-wM',
      'https://img.youtube.com/vi/3UWi44yN-wM/0.jpg',
      3,
      "Standing Barbell Calf Raise",
      "ScottHermanFitness",
      "leg"),
  Video(
      '4',
      'Seated Leg Extension',
      'https://www.youtube.com/watch?v=0fl1RRgJ83I',
      'https://img.youtube.com/vi/0fl1RRgJ83I/0.jpg',
      1,
      "Seated Leg Raise",
      "Muscle & Strength",
      "leg"),
  Video(
      '5',
      'Leg Press',
      'https://www.youtube.com/watch?v=sEM_zo9w2ss',
      'https://img.youtube.com/vi/sEM_zo9w2ss/0.jpg',
      2,
      "Leg Press",
      "Muscle & Strength",
      "leg"),
  Video(
      '6',
      'Barbell Back Squat',
      'https://www.youtube.com/watch?v=R2dMsNhN3DE',
      'https://img.youtube.com/vi/R2dMsNhN3DE/0.jpg',
      3,
      "Barbell Back Squat",
      "Muscle & Strength",
      "leg"),
  Video(
      '7',
      'How To: Prone Leg Curl (Cybex)',
      'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
      'https://img.youtube.com/vi/1Tq3QdYUuHs/0.jpg',
      1,
      "Prone Leg Curl",
      "ScottHermanFitness",
      "leg"),
  Video(
      '8',
      'How to Do Leg Raises',
      'https://www.youtube.com/watch?v=JB2oyawG9KI',
      'https://img.youtube.com/vi/JB2oyawG9KI/0.jpg',
      1,
      "Leg Raises",
      "LIVESTRONG.COM",
      "leg"),
];

final List<Video> shoulder = [
  Video(
      '1',
      'Dumbbell Seated Overhead Press',
      'https://www.youtube.com/watch?v=-Xa2xYhPl-0',
      'https://img.youtube.com/vi/-Xa2xYhPl-0/0.jpg',
      2,
      "Dumbbell Seated Overhead Press",
      "Goodlife Health Clubs",
      "shoulder"),
  Video(
      '2',
      'Seated Barbell Military Press',
      'https://www.youtube.com/watch?v=4HCgc4S0z9g',
      'https://img.youtube.com/vi/4HCgc4S0z9g/0.jpg',
      3,
      "Seated Barbell Military Press",
      "Boser Built",
      "shoulder"),
  Video(
      '3',
      'Wide Grip Barbell Upright Row',
      'https://www.youtube.com/watch?v=IzBZ-9NSVVU',
      'https://img.youtube.com/vi/IzBZ-9NSVVU/0.jpg',
      3,
      "Wide Grip Barbell Upright Row",
      "Broser Built",
      "shoulder"),
  Video(
      '4',
      'Kourtney Thomas — Arnold Press',
      'https://www.youtube.com/watch?v=zvId5KzQGwk',
      'https://img.youtube.com/vi/zvId5KzQGwk/0.jpg',
      1,
      "Arnold Press",
      "Girls Gone Strong",
      "shoulder"),
  Video(
      '5',
      'Kourtney Thomas — Rear Delt Raise',
      'https://www.youtube.com/watch?v=ofMGVun42bc',
      'https://img.youtube.com/vi/ofMGVun42bc/0.jpg',
      1,
      "Rear Deltoid Raise",
      "Girls Gone Strong",
      "shoulder"),
  Video(
      '6',
      'Dumbbell Clean & Press Tutorial',
      'https://www.youtube.com/watch?v=4MKfeQDkkNY',
      'https://img.youtube.com/vi/4MKfeQDkkNY/0.jpg',
      2,
      "Dumbbell Press and Clean",
      "PhD Nutrition",
      "shoulder"),
  Video(
      '7',
      'How to Do Dumbbell Shrugs',
      'https://www.youtube.com/watch?v=g6qbq4Lf1FI',
      'https://img.youtube.com/vi/g6qbq4Lf1FI/0.jpg',
      1,
      "Dumbbell Shrugs",
      "LIVESTRONG.COM",
      "shoulder"),
  Video(
      '8',
      'How to Perfect Your Dumbbell Row',
      'https://www.youtube.com/watch?v=roCP6wCXPqo',
      'https://img.youtube.com/vi/roCP6wCXPqo/0.jpg',
      2,
      "Dumbbell Row",
      "Men's Health",
      "shoulder"),
];

final List<Video> yoga = [
  Video(
      '1',
      '7 Yoga Poses for Upper Back Pain',
      'https://www.youtube.com/watch?v=jeWbzefarHY',
      'https://img.youtube.com/vi/jeWbzefarHY/0.jpg',
      2,
      '7 Yoga Poses for Upper Back Pain',
      "ePainAssist",
      "yoga"),
  Video(
      '2',
      '30 BASIC BEGINNER YOGA POSES | Yoga for beginners',
      'https://www.youtube.com/watch?v=rylnYQ5Eunc',
      'https://img.youtube.com/vi/rylnYQ5Eunc/0.jpg',
      1,
      "Beginner Yoga",
      "Yoga with Uliana",
      "yoga"),
  Video(
      '3',
      'How to Do a Cat Cow Pose for Energy | Yoga',
      'https://www.youtube.com/watch?v=kqnua4rHVVA',
      'https://img.youtube.com/vi/kqnua4rHVVA/0.jpg',
      1,
      "How to Do a Cat Cow Pose for Energy",
      "Howcast",
      "yoga"),
  Video(
      '4',
      'Cobra Yoga Pose',
      'https://www.youtube.com/watch?v=fOdrW7nf9gw',
      'https://img.youtube.com/vi/fOdrW7nf9gw/0.jpg',
      1,
      "Cobra Yoga Pose",
      "The Art of Living",
      "yoga"),
  Video(
      '5',
      '7 Best Yoga Poses for Spine Health',
      'https://www.youtube.com/watch?v=iQXcwrcSCbE',
      'https://img.youtube.com/vi/iQXcwrcSCbE/0.jpg',
      1,
      "7 Best Yoga Poses for Spine Health",
      "ePainAssist",
      "yoga"),
  Video(
      '6',
      '5 Yoga Asanas To Stimulate Your Nervous System',
      'https://www.youtube.com/watch?v=5QCodeo4zt4',
      'https://img.youtube.com/vi/5QCodeo4zt4/0.jpg',
      1,
      '5 Yoga Asanas To Stimulate Your Nervous System',
      'VENTUNO YOGA',
      "yoga"),
  Video(
      '7',
      'Yoga Poses for Kidney Health',
      'https://www.youtube.com/watch?v=y_lNdXJjQDc',
      'https://img.youtube.com/vi/y_lNdXJjQDc/0.jpg',
      1,
      'Yoga Poses for Kidney Health',
      "VENTUNO YOGA",
      "yoga"),
  Video(
      '8',
      '5 Effective Yoga Asanas To Flush Out Kidney Stones',
      'https://www.youtube.com/watch?v=ZllDiYDBMsg',
      'https://img.youtube.com/vi/ZllDiYDBMsg/0.jpg',
      1,
      '5 Effective Yoga Asanas To Flush Out Kidney Stones',
      "VENTUNO YOGA",
      "yoga"),
];
